#!/usr/bin/python3

import datetime

now = datetime.datetime.now()
local_now = now.astimezone()
local_tz = local_now.tzinfo
local_tzname = local_tz.tzname(local_now)
print(local_tzname)
print(local_tz.utcoffset(local_now))
print(local_tz.dst(local_now))
